import os
import argparse
import numpy as np
import pickle

from pycocotools import mask as COCOmask
from dummy_datasets import get_coco_dataset, get_ade_dataset
from coco_format import *

def convert_from_cls_format(cls_boxes, cls_segms, cls_keyps):
    """Convert from the class boxes/segms/keyps format generated by the testing
    code.
    """
    box_list = [b for b in cls_boxes if len(b) > 0]
    if len(box_list) > 0:
        boxes = np.concatenate(box_list)
    else:
        boxes = None
    if cls_segms is not None:
        segms = [s for slist in cls_segms for s in slist]
    else:
        segms = None
    if cls_keyps is not None:
        keyps = [k for klist in cls_keyps for k in klist]
    else:
        keyps = None
    classes = []
    for j in range(len(cls_boxes)):
        classes += [j] * len(cls_boxes[j])
    return boxes, segms, keyps, classes


def make_annotations(detections, im_list):
    annotations = []
    for i, im_name in enumerate(im_list):
        print(i, im_name, len(annotations))

        cls_boxes, cls_segms, cls_keyps = detections[im_name]
        boxes, segms, keypoints, classes = convert_from_cls_format(cls_boxes, cls_segms, cls_keyps)
        if segms is None:
            continue

        for j in range(len(segms)):
            segm = segms[j]
            score = boxes[j, -1]
            cat = classes[j]

            mask = COCOmask.decode(segm)

            ann = make_ann(mask)
            ann["image_id"] = i + 1
            ann["category_id"] = int(cat)
            ann["id"] = len(annotations) + 1
            ann["score"] = float(score)
            annotations.append(ann)
    return annotations

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dataset', type=str, default="ade20k")
    parser.add_argument('-s', '--split', type=str, default="val")
    parser.add_argument('-p', '--pkl', type=str, required=True)
    parser.add_argument('-c', '--categories', type=str, default="coco")
    args = parser.parse_args()

    data_dir = "../data/{}/".format(args.dataset)
    im_dir = os.path.join(data_dir, "images")

    # Load im_list
    im_list = os.path.join(data_dir, "im_lists/{}.txt".format(args.split))
    with open(im_list,'r') as f:
        im_list = f.read().splitlines()

    # Load cat_list
    cat_list = []
    if args.categories == "coco":
        cat_list = get_coco_dataset()
    elif args.categories == "ade":
        cat_list = get_ade_dataset()

    detections = None
    with open(args.pkl, 'rb') as f:
        detections = pickle.load(f)

    annotations = make_annotations(detections, im_list)
    images = make_images(im_list, im_dir)
    categories = make_categories(cat_list)

    out_dir = os.path.dirname(args.pkl)
    out_file = os.path.join(out_dir, "predictions.json")
    save_ann_fn(images, annotations, categories, out_file)


